.\"                                      Hey, EMACS: -*- nroff -*-
.TH BOINCTUI 1 "21-JAN-2016"
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
boinctui \- Fullscreen text mode manager for BOINC client
.SH SYNOPSIS
.B boinctui
.SH DESCRIPTION
BOINC can be configured in many ways. And the monitoring of
scientific progress contributed to one's own machines is
rewarding. For remote machines or to avoid moving the hands
of your keyboard, this package provides, all for your UNIX
command line:
.br
 * Fullscreen curses based text user interface
.br
 * Switch between several BOINC clients hosts via hot key
.br
 * View task list (run, queue, suspend e.t.c state)
.br
 * View message list
.br
 * Suspend/Resume/Abort tasks
.br
 * Update/Suspend/Resume/Reset/No New Task/Allow New Task for projects
.br
 * Toggle activity state GPU and CPU tasks
.br
 * Run benchmarks
.br
 * Manage BOINC client on remote hosts via boinc_gui protocol 

.SH SEE ALSO
.BR boinc-manager (1),
.br
https://github.com/suleman1971/boinctui
